version: '3'
services:
  app1:
    build: ./app1
  app2:
    build: ./app2
  app3:
    build: ./app3
  
  nginx:
    build: ./nginx 
    ports:
    - "9000:80"
    depends_on:
      - app1
      - app2
      - app3